pipeline {
    agent any

    tools {
        maven "maven-3.8.1"
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {

        stage('Build') {
            steps {
                sh 'mvn -f springboot-first-app/pom.xml clean package'
            }
        }
    }
}