pipeline {
    agent any

    tools {
        maven "maven-3.8.1"
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t springboot-first-app-dockerized1 springboot-first-app/'
            }
        }
    }
}